# Generated by Django 4.2.4 on 2023-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
